### ISSUE TITLE
Needs switching to GHA

### ISSUE THREAD

**Issue by cderv** [yihui/homebrew-cran-extra#1]
@yihui this repo also is no more build on travis due to the limit. 
Maybe having switched the other will let some credit for this one. 

Do you want also a PR on this one for migrating the travis.yml content to a GHA workflow ? 
Should be close to what I have done for travis-bin.

**Comment by yihui** [comment]
Yes, please. Thanks!

**Comment by yihui** [comment]
This has been done in the past few days.
