### ISSUE TITLE
RGtk2 issue

### ISSUE THREAD

**Issue by yufree** [yihui/homebrew-cran-extra#2]
It seems `RGtk2` and `cairoDevice` packages have been removed from CRAN for a [while](https://cran.r-project.org/web/packages/cairoDevice/index.html). 

In this case, `xfun:::brew_dep('RGtk2')` will return `NULL`. Then I was trapped again in wired compile error of `RGtk2` [issue](https://yihui.org/en/2018/01/install-rgtk2-macos/). The error information is not informative:

```
make: *** [cairoConversion.o] Error 1
ERROR: compilation failed for package ‘RGtk2’
```

I wonder if it's possible to build the binary here for mac os from `cran/RGtk2` and `cran/cairoDevice`? Thanks!

**Comment by yihui** [comment]
I'm afraid it's not possible. Neither **cairoDevice** nor **RGtk2** could be built. There are C errors that I don't understand and can't fix: https://github.com/yihui/homebrew-cran-extra/actions/runs/3194284852/jobs/5213702664#step:6:480 I'll need help from other experts.
